export * from './Footer'
export * from './Header'
export * from './CartComponent'
export * from './Input'
export * from './ButtonSubmit'
export * from './ButtonBuyNow'
export * from './ProductSize'
export * from './ProductDefaul'
export * from './ProductContent'
export * from './ProductCenter'
export * from './Collections'
export * from './Tags'
export * from './Service'
export * from './FollowUs'
export * from './ProductCenterHorizontal'
// export * from './ProductSlider'
export * from './OnBoarding'
export * from './OnBoardingItem'
export * from './Paginator'
////
export * from './MaterialTabs'
export * from './All'
export * from './Apparel'
export * from './Bag'
export * from './Dress'
export * from './Tshirt'
//////////
export * from './Blog'

export * from './TabBlog'
export * from './Fashion'
export * from './Promo'
export * from './LookBook'
export * from './Policy'
export * from './Sa'

// export * from './ProductSliderItems'